Graph LR

ClassDef red fill:#e33,color:#3ee,stroke:#3ee,stroke-width:2px;
ClassDef grn fill:#3e3,color:#e3e,stroke:#e3e,stroke-width:2px;
ClassDef blu fill:#33e,color:#ee3,stroke:#ee3,stroke-width:2px;

style box fill:#3e3,color:#e3e,stroke:#e3e,stroke-width:2px;

Subgraph box[My Box]
A:::red --> B:::grn --> C:::blu
End

linkstyle 0 fill:#e33,color:#3ee,stroke:#3ee,stroke-width:2px;
linkstyle 1 fill:#3e3,color:#e3e,stroke:#e3e,stroke-width:2px;
